nodeVersion: 22.12.0
pmOnFail: download
packages:
  - docs

catalog:
  '@types/node': ^26.1.2
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
  react: 19.3.0
  react-dom: 19.3.0
  typescript: 7.0.2

allowBuilds:
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  keytar: false
  mongodb-memory-server: true
  oxc-resolver: true
  puppeteer: false
  sharp: true
minimumReleaseAgeExclude:
  - '@pnpm/exe.android-arm64@12.8.2'
  - '@pnpm/exe.android-x64@12.8.2'
  - '@pnpm/exe.darwin-arm64@12.8.2'
  - '@pnpm/exe.darwin-x64@12.8.2'
  - '@pnpm/exe.freebsd-x64@12.8.2'
  - '@pnpm/exe.linux-arm64-musl@12.8.2'
  - '@pnpm/exe.linux-arm64@12.8.2'
  - '@pnpm/exe.linux-ppc64@12.8.2'
  - '@pnpm/exe.linux-riscv64@12.8.2'
  - '@pnpm/exe.linux-s390x@12.8.2'
  - '@pnpm/exe.linux-x64-musl@12.8.2'
  - '@pnpm/exe.linux-x64@12.8.2'
  - '@pnpm/exe.win32-arm64@12.8.2'
  - '@pnpm/exe.win32-x64@12.8.2'
  - pnpm@12.8.2
