name: Question / Support
description: Ask a question or get help with using the plugin
title: '[Question]: '
labels: ['question']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Before asking:** Please check [documentation](https://github.com/maximseshuk/payload-storage-bunny#readme), [migration guide](https://github.com/maximseshuk/payload-storage-bunny/blob/main/docs/migration-guide.md), and [existing issues](https://github.com/maximseshuk/payload-storage-bunny/issues).

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you need help with?
      placeholder: |
        Please tell us:
        - What you're trying to accomplish
        - What problem you're encountering
        - What you've tried so far
        - Any error messages you're seeing
    validations:
      required: true

  - type: textarea
    id: current-config
    attributes:
      label: Current Configuration (if relevant)
      description: Share your plugin setup (**remove API keys and sensitive data**)
      placeholder: |
        ```typescript
        bunnyStorage({
          collections: {
            media: true,
          },
          storage: {
            apiKey: 'REDACTED',
            hostname: 'example.b-cdn.net',
            zoneName: 'your-zone',
          },
        })
        ```
      render: typescript
