blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://payload-storage-bunny.seshuk.im
    about: Check the documentation for setup and configuration guides
  - name: 🔄 Upgrade Guide
    url: https://payload-storage-bunny.seshuk.im/upgrade-guide
    about: How to upgrade from an older major version
